# Generated by Django 3.1.2 on 2021-01-23 03:31

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNumero',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('primos', jsonfield.fields.JSONField()),
                ('primos_gemelos', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
